import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { env } from '../config/env.js';
import { UserModel } from '../models/user.model.js';
import { IncidentModel } from '../models/incident.model.js';
import { ResourceModel } from '../models/resource.model.js';
import { ResponseTeamModel } from '../models/team.model.js';
import { FacilityModel } from '../models/facility.model.js';

const seedDatabase = async () => {
  try {
    console.log('[Seed] Connecting to MongoDB...');
    await mongoose.connect(env.MONGODB_URI);
    console.log('[Seed] Connected to database.');

    // 1. Clear existing collections
    console.log('[Seed] Clearing existing collections...');
    await Promise.all([
      UserModel.deleteMany({}),
      IncidentModel.deleteMany({}),
      ResourceModel.deleteMany({}),
      ResponseTeamModel.deleteMany({}),
      FacilityModel.deleteMany({}),
    ]);
    console.log('[Seed] Collections cleared.');

    // 2. Seed Users (6 Users across all roles)
    console.log('[Seed] Seeding Users...');
    const defaultPassword = await bcrypt.hash('Emergency@2026', 10);

    const users = [
      {
        name: 'Commander Sarah Jenkins',
        email: 'admin@emergency.ps9.gov',
        password: defaultPassword,
        role: 'ADMIN',
        department: 'Central Crisis Executive Command',
      },
      {
        name: 'Operator David Chen',
        email: 'operator@emergency.ps9.gov',
        password: defaultPassword,
        role: 'OPERATOR',
        department: 'Emergency Telemetry & 911 Intake',
      },
      {
        name: 'Captain Marcus Rodriguez',
        email: 'field@emergency.ps9.gov',
        password: defaultPassword,
        role: 'FIELD_COORDINATOR',
        department: 'Fire & Urban Rescue Brigade',
      },
      {
        name: 'Dr. Elena Rostova',
        email: 'medical@emergency.ps9.gov',
        password: defaultPassword,
        role: 'MEDICAL_COORDINATOR',
        department: 'Emergency Trauma Network',
      },
      {
        name: 'Inspector Rajiv Sharma',
        email: 'police@emergency.ps9.gov',
        password: defaultPassword,
        role: 'FIELD_COORDINATOR',
        department: 'Highway & Tactical Law Enforcement',
      },
      {
        name: 'Operator Maya Patel',
        email: 'maya.patel@emergency.ps9.gov',
        password: defaultPassword,
        role: 'OPERATOR',
        department: 'Hazardous Materials Control',
      },
    ];

    await UserModel.insertMany(users);
    console.log(`[Seed] Seeded ${users.length} Users.`);

    // 3. Seed Response Teams (8 Teams)
    console.log('[Seed] Seeding Response Teams...');
    const teams = [
      {
        teamId: 'TEAM-FT04',
        name: 'Fire Team 04 (Industrial Foam)',
        type: 'FIRE',
        status: 'ASSIGNED',
        members: ['Captain Rodriguez', 'Lt. Miller', 'Spec. Diaz', 'Spec. Adams', 'Tech. Vance', 'Tech. Cole'],
        vehicleId: 'FT-204',
        location: {
          latitude: 28.6250,
          longitude: 77.2020,
          address: 'Industrial Ring Sector 4 Gate, Zone 3',
          geometry: { type: 'Point', coordinates: [77.2020, 28.6250] },
        },
        capabilities: ['FOAM_CURTAIN', 'HYDROCARBON_FIRE', 'HIGH_PRESSURE_PUMP'],
        currentAssignment: 'ER-2048',
        radioChannel: 'CH-04 FIRE TAC',
      },
      {
        teamId: 'TEAM-FT01',
        name: 'Fire Team 01 (Aerial Ladder Squad)',
        type: 'FIRE',
        status: 'AVAILABLE',
        members: ['Capt. Harris', 'Lt. Gomez', 'Firefighter Bell', 'Firefighter Brooks', 'Operator Stone'],
        vehicleId: 'FT-101',
        location: {
          latitude: 28.6328,
          longitude: 77.2197,
          address: 'Central Fire HQ, Station 1',
          geometry: { type: 'Point', coordinates: [77.2197, 28.6328] },
        },
        capabilities: ['HIGHRISE_LADDER', 'SEARCH_RESCUE', 'VENTILATION'],
        radioChannel: 'CH-01 CMD',
      },
      {
        teamId: 'TEAM-AM07',
        name: 'Ambulance 07 (Mobile Trauma ICU)',
        type: 'MEDICAL',
        status: 'ASSIGNED',
        members: ['Dr. Rostova', 'Paramedic Hayes', 'Paramedic Wright', 'Driver Simmons'],
        vehicleId: 'AM-07',
        location: {
          latitude: 28.6190,
          longitude: 77.2040,
          address: 'South Arterial Transit Corridor',
          geometry: { type: 'Point', coordinates: [77.2040, 28.6190] },
        },
        capabilities: ['ADVANCED_CARDIAC_LIFE_SUPPORT', 'BURN_STABILIZATION', 'MOBILE_ICU'],
        currentAssignment: 'ER-2048',
        radioChannel: 'CH-09 MED NET',
      },
      {
        teamId: 'TEAM-AM02',
        name: 'Ambulance 02 (Rapid Cardiac Paramedic)',
        type: 'MEDICAL',
        status: 'BUSY',
        members: ['Paramedic Foster', 'Paramedic Campbell', 'Driver Ortiz'],
        vehicleId: 'AM-02',
        location: {
          latitude: 28.5800,
          longitude: 77.1700,
          address: 'NH-48 Expressway Toll Gate',
          geometry: { type: 'Point', coordinates: [77.1700, 28.5800] },
        },
        capabilities: ['TRIAGE', 'TRAUMA_PACK', 'TELEMEDICINE'],
        currentAssignment: 'ER-2050',
        radioChannel: 'CH-07 DISPATCH',
      },
      {
        teamId: 'TEAM-PD02',
        name: 'Police Tactical Squad 02',
        type: 'POLICE',
        status: 'ON_SCENE',
        members: ['Sgt. Barnes', 'Officer Taylor', 'Officer Evans', 'Officer Murphy'],
        vehicleId: 'PD-102',
        location: {
          latitude: 28.6289,
          longitude: 77.2065,
          address: 'Apex Petrochemical Gate 1',
          geometry: { type: 'Point', coordinates: [77.2065, 28.6289] },
        },
        capabilities: ['PERIMETER_CORDON', 'EVACUATION_ESCORT', 'TRAFFIC_DIVERT'],
        currentAssignment: 'ER-2048',
        radioChannel: 'CH-02 POL TAC',
      },
      {
        teamId: 'TEAM-PD05',
        name: 'Highway Patrol Squad 05',
        type: 'POLICE',
        status: 'AVAILABLE',
        members: ['Inspector Sharma', 'Officer Khan', 'Officer Gupta'],
        vehicleId: 'PD-105',
        location: {
          latitude: 28.5720,
          longitude: 77.1620,
          address: 'South Expressway Outpost',
          geometry: { type: 'Point', coordinates: [77.1620, 28.5720] },
        },
        capabilities: ['HIGHWAY_BLOCKADE', 'INTERCEPTOR_CRUISE'],
        radioChannel: 'CH-05 HIGHWAY',
      },
      {
        teamId: 'TEAM-HZ01',
        name: 'Hazmat Chemical Neutralization Alpha',
        type: 'FIRE',
        status: 'BUSY',
        members: ['Cmdr. Becker', 'Spec. Wong', 'Spec. Jensen', 'Spec. Rossi', 'Chemist Al-Sayed'],
        vehicleId: 'HZ-901',
        location: {
          latitude: 28.6410,
          longitude: 77.2340,
          address: 'Docklands Cargo Bay 14',
          geometry: { type: 'Point', coordinates: [77.2340, 28.6410] },
        },
        capabilities: ['CHLORINE_NEUTRALIZATION', 'LEVEL_A_SUITS', 'ATMOSPHERIC_SCRUBBING'],
        currentAssignment: 'ER-2049',
        radioChannel: 'CH-12 HAZMAT',
      },
      {
        teamId: 'TEAM-RT03',
        name: 'Rescue Squad 03 (Aquatic & Collapsed Structure)',
        type: 'RESCUE',
        status: 'AVAILABLE',
        members: ['Capt. Larson', 'Diver Flynn', 'Diver Price', 'Rescue Tech Roy', 'K9 Handler Fox'],
        vehicleId: 'RT-303',
        location: {
          latitude: 28.6500,
          longitude: 77.1950,
          address: 'Sector 5 Riverbank Depot',
          geometry: { type: 'Point', coordinates: [77.1950, 28.6500] },
        },
        capabilities: ['SWIFT_WATER_RESCUE', 'INFLATABLE_ZODIAC', 'SONAR_DEPTH_DETECTION'],
        radioChannel: 'CH-08 RESCUE',
      },
    ];

    await ResponseTeamModel.insertMany(teams);
    console.log(`[Seed] Seeded ${teams.length} Response Teams.`);

    // 4. Seed Facilities (8 Facilities)
    console.log('[Seed] Seeding Facilities...');
    const facilities = [
      {
        facilityId: 'HOSP-01',
        name: 'Apex Trauma & Specialty Hospital',
        type: 'HOSPITAL',
        location: {
          latitude: 28.6220,
          longitude: 77.1980,
          address: 'Plot 12, Industrial Boulevard West',
          geometry: { type: 'Point', coordinates: [77.1980, 28.6220] },
        },
        capacity: 450,
        availableCapacity: 12,
        specializations: ['TRAUMA_LEVEL_1', 'BURN_INTENSIVE_CARE', 'CHEMICAL_DECONTAMINATION'],
        status: 'OPERATIONAL',
        contactNumber: '+91-11-2334-0101',
      },
      {
        facilityId: 'HOSP-02',
        name: 'Metropolitan Government General Hospital',
        type: 'HOSPITAL',
        location: {
          latitude: 28.6360,
          longitude: 77.2240,
          address: 'Central Square Civic Ring',
          geometry: { type: 'Point', coordinates: [77.2240, 28.6360] },
        },
        capacity: 820,
        availableCapacity: 14,
        specializations: ['PULMONOLOGY', 'BURN_CARE', 'MASS_CASUALTY_SURGERY'],
        status: 'OPERATIONAL',
        contactNumber: '+91-11-2334-0202',
      },
      {
        facilityId: 'HOSP-03',
        name: 'South Expressway Emergency Clinic',
        type: 'HOSPITAL',
        location: {
          latitude: 28.5880,
          longitude: 77.1820,
          address: 'Sector 8 Junction Highway Link',
          geometry: { type: 'Point', coordinates: [77.1820, 28.5880] },
        },
        capacity: 210,
        availableCapacity: 2,
        specializations: ['POLYTRAUMA', 'ORTHOPEDIC_SURGERY', 'AMBULANCE_BAY'],
        status: 'OPERATIONAL',
        contactNumber: '+91-11-2334-0303',
      },
      {
        facilityId: 'HOSP-04',
        name: 'Port Maritime Military Medical Base',
        type: 'HOSPITAL',
        location: {
          latitude: 28.6480,
          longitude: 77.2420,
          address: 'Docklands Naval Perimeter Gate',
          geometry: { type: 'Point', coordinates: [77.2420, 28.6480] },
        },
        capacity: 340,
        availableCapacity: 18,
        specializations: ['HAZMAT_TOXICOLOGY', 'HYPERBARIC_CHAMBERS', 'TRAUMA_SURGERY'],
        status: 'OPERATIONAL',
        contactNumber: '+91-11-2334-0404',
      },
      {
        facilityId: 'HOSP-05',
        name: 'Saint Jude Memorial Community Care',
        type: 'HOSPITAL',
        location: {
          latitude: 28.6600,
          longitude: 77.2010,
          address: 'Riverbank North Colony',
          geometry: { type: 'Point', coordinates: [77.2010, 28.6600] },
        },
        capacity: 180,
        availableCapacity: 0,
        specializations: ['GENERAL_MEDICINE', 'PEDIATRICS'],
        status: 'DIVERTING',
        contactNumber: '+91-11-2334-0505',
      },
      {
        facilityId: 'SHELTER-01',
        name: 'Sector 4 Community Disaster Evacuation Shelter',
        type: 'SHELTER',
        location: {
          latitude: 28.6300,
          longitude: 77.1950,
          address: 'Sports Complex Pavillion, Sector 4',
          geometry: { type: 'Point', coordinates: [77.1950, 28.6300] },
        },
        capacity: 1200,
        availableCapacity: 840,
        specializations: ['TEMPORARY_LODGING', 'CLEAN_WATER', 'EMERGENCY_RATIONS'],
        status: 'OPERATIONAL',
        contactNumber: '+91-11-2334-0606',
      },
      {
        facilityId: 'SHELTER-02',
        name: 'River Basin Elevated Relief Pavilion',
        type: 'SHELTER',
        location: {
          latitude: 28.6580,
          longitude: 77.1980,
          address: 'Municipal High Grounds, Zone 5',
          geometry: { type: 'Point', coordinates: [77.1980, 28.6580] },
        },
        capacity: 800,
        availableCapacity: 550,
        specializations: ['FLOOD_RELIEF', 'POWER_GENERATORS', 'MEDICAL_STATION'],
        status: 'OPERATIONAL',
        contactNumber: '+91-11-2334-0707',
      },
      {
        facilityId: 'CENTER-01',
        name: 'Central Incident Command Complex HQ',
        type: 'EMERGENCY_CENTER',
        location: {
          latitude: 28.6320,
          longitude: 77.2180,
          address: 'Civic Center Tower 1, Connaught Ring',
          geometry: { type: 'Point', coordinates: [77.2180, 28.6320] },
        },
        capacity: 300,
        availableCapacity: 120,
        specializations: ['DISASTER_DISPATCH', 'SATELLITE_UPLINK', 'MULTI_AGENCY_COORDINATION'],
        status: 'OPERATIONAL',
        contactNumber: '+91-11-2334-0808',
      },
    ];

    await FacilityModel.insertMany(facilities);
    console.log(`[Seed] Seeded ${facilities.length} Facilities.`);

    // 5. Seed Resources (12 Resources)
    console.log('[Seed] Seeding Resources...');
    const resources = [
      {
        resourceId: 'RES-VEH-01',
        name: 'Heavy Foam Tender FT-204',
        type: 'VEHICLE',
        status: 'ASSIGNED',
        location: {
          latitude: 28.6250,
          longitude: 77.2020,
          address: 'Industrial Ring Sector 4 Gate, Zone 3',
          geometry: { type: 'Point', coordinates: [77.2020, 28.6250] },
        },
        capabilities: ['FOAM_SPRAY', '10000_LITER_TANK', 'REMOTE_MONITOR'],
        capacity: 6,
        currentAssignment: 'ER-2048',
      },
      {
        resourceId: 'RES-VEH-02',
        name: 'Critical Care Mobile ICU AM-07',
        type: 'AMBULANCE',
        status: 'ASSIGNED',
        location: {
          latitude: 28.6190,
          longitude: 77.2040,
          address: 'South Arterial Transit Corridor',
          geometry: { type: 'Point', coordinates: [77.2040, 28.6190] },
        },
        capabilities: ['VENTILATOR', 'DEFIBRILLATOR', 'TELEMETRY_LINK'],
        capacity: 2,
        currentAssignment: 'ER-2048',
      },
      {
        resourceId: 'RES-VEH-03',
        name: 'High-Speed Interceptor Patrol PD-102',
        type: 'POLICE_TEAM',
        status: 'ASSIGNED',
        location: {
          latitude: 28.6289,
          longitude: 77.2065,
          address: 'Apex Petrochemical Gate 1',
          geometry: { type: 'Point', coordinates: [77.2065, 28.6289] },
        },
        capabilities: ['SIREN', 'GPS_RADAR', 'BALLISTIC_PROTECTION'],
        capacity: 4,
        currentAssignment: 'ER-2048',
      },
      {
        resourceId: 'RES-VEH-04',
        name: 'Hazmat Decontamination Unit HZ-901',
        type: 'EQUIPMENT',
        status: 'BUSY',
        location: {
          latitude: 28.6410,
          longitude: 77.2340,
          address: 'Docklands Cargo Bay 14',
          geometry: { type: 'Point', coordinates: [77.2340, 28.6410] },
        },
        capabilities: ['CHLORINE_SCRUBBER', 'AIR_ISOLATION', 'PORTABLE_SHOWER'],
        capacity: 8,
        currentAssignment: 'ER-2049',
      },
      {
        resourceId: 'RES-EQ-01',
        name: 'Autonomous Drone Recon Swarm Alpha (4 UAVs)',
        type: 'EQUIPMENT',
        status: 'BUSY',
        location: {
          latitude: 28.6289,
          longitude: 77.2065,
          address: 'Apex Petrochemical Airspace Sector 4',
          geometry: { type: 'Point', coordinates: [77.2065, 28.6289] },
        },
        capabilities: ['THERMAL_IMAGING', 'GAS_SENSING', '4K_STREAMING'],
        capacity: 4,
        currentAssignment: 'ER-2048',
      },
      {
        resourceId: 'RES-EQ-02',
        name: 'High-Volume Flood De-Watering Pumps (6 Units)',
        type: 'EQUIPMENT',
        status: 'AVAILABLE',
        location: {
          latitude: 28.6550,
          longitude: 77.1920,
          address: 'Riverbank Station 4 Depot',
          geometry: { type: 'Point', coordinates: [77.1920, 28.6550] },
        },
        capabilities: ['SUBMERSIBLE_PUMP', '15000_GPM', 'DIESEL_BACKUP'],
        capacity: 6,
      },
      {
        resourceId: 'RES-EQ-03',
        name: 'Mobile Mass Casualty Triage Trailer',
        type: 'EQUIPMENT',
        status: 'AVAILABLE',
        location: {
          latitude: 28.6360,
          longitude: 77.2240,
          address: 'Metro General Compound',
          geometry: { type: 'Point', coordinates: [77.2240, 28.6360] },
        },
        capabilities: ['50_BED_TENT', 'OXYGEN_MANIFOLD', 'TRIAGE_TAGGING'],
        capacity: 50,
      },
      {
        resourceId: 'RES-EQ-04',
        name: 'Satellite Mobile Mesh Telemetry Node',
        type: 'EQUIPMENT',
        status: 'AVAILABLE',
        location: {
          latitude: 28.6320,
          longitude: 77.2180,
          address: 'Civil Center Tower Depot',
          geometry: { type: 'Point', coordinates: [77.2180, 28.6320] },
        },
        capabilities: ['LOW_LATENCY_SAT_UPLINK', 'RADIO_CROSS_PATCH', '5G_MESH'],
        capacity: 100,
      },
      {
        resourceId: 'RES-VEH-05',
        name: 'Aerial Ladder Platform 55m FT-101',
        type: 'FIRE_TEAM',
        status: 'AVAILABLE',
        location: {
          latitude: 28.6328,
          longitude: 77.2197,
          address: 'Central Fire HQ, Station 1',
          geometry: { type: 'Point', coordinates: [77.2197, 28.6328] },
        },
        capabilities: ['55M_AERIAL_LADDER', 'WATER_CANNON', 'STRETCHER_LIFT'],
        capacity: 5,
      },
      {
        resourceId: 'RES-VEH-06',
        name: 'Advanced Cardiac Ambulance AM-02',
        type: 'AMBULANCE',
        status: 'BUSY',
        location: {
          latitude: 28.5800,
          longitude: 77.1700,
          address: 'NH-48 Expressway Toll Gate',
          geometry: { type: 'Point', coordinates: [77.1700, 28.5800] },
        },
        capabilities: ['ALS_RESUSCITATION', 'PEDIATRIC_KIT'],
        capacity: 2,
        currentAssignment: 'ER-2050',
      },
      {
        resourceId: 'RES-VEH-07',
        name: 'Highway Interceptor Cruiser PD-105',
        type: 'POLICE_TEAM',
        status: 'AVAILABLE',
        location: {
          latitude: 28.5720,
          longitude: 77.1620,
          address: 'South Expressway Outpost',
          geometry: { type: 'Point', coordinates: [77.1620, 28.5720] },
        },
        capabilities: ['SPEED_DETECTION', 'ROAD_BLOCK_KIT'],
        capacity: 4,
      },
      {
        resourceId: 'RES-VEH-08',
        name: 'Amphibious All-Terrain Rescue Rig RT-303',
        type: 'RESCUE_TEAM',
        status: 'AVAILABLE',
        location: {
          latitude: 28.6500,
          longitude: 77.1950,
          address: 'Sector 5 Riverbank Depot',
          geometry: { type: 'Point', coordinates: [77.1950, 28.6500] },
        },
        capabilities: ['AMPHIBIOUS_DRIVE', 'WATER_JET_WINCH', 'FLOOD_BOAT_TOW'],
        capacity: 8,
      },
    ];

    await ResourceModel.insertMany(resources);
    console.log(`[Seed] Seeded ${resources.length} Resources.`);

    // 6. Seed Incidents (22 Incidents covering diverse types, severities, priorities)
    console.log('[Seed] Seeding Incidents...');
    const incidents = [
      {
        incidentId: 'ER-2048',
        title: 'Industrial Chemical Refinery Fire & Explosion Threat',
        type: 'INDUSTRIAL_ACCIDENT',
        description: 'Multi-point thermal runaway detected at chemical refinery storage tank block 4. High explosive vapor risk. 7 converging 911 calls correlated with IoT industrial pressure sensors. Immediate foam suppression and evacuation active.',
        location: {
          latitude: 28.6289,
          longitude: 77.2065,
          address: 'Apex Petrochemical Complex, Sector 4, Industrial Zone 3',
          geometry: { type: 'Point', coordinates: [77.2065, 28.6289] },
        },
        severity: 'CRITICAL',
        priority: 'P1',
        confidence: 94,
        status: 'RESPONDING',
        source: 'SENSOR',
        reports: [
          {
            reportId: 'REP-101',
            source: 'SENSOR',
            text: 'Sensor #TH-882 heat threshold exceeded 680°C in Tank Block B.',
            reliability: 98,
            reportedAt: new Date(Date.now() - 30 * 60000),
          },
          {
            reportId: 'REP-102',
            source: 'EMERGENCY_CALL',
            text: 'Detonation heard, heavy black smoke column visible from 2km.',
            reliability: 95,
            reportedAt: new Date(Date.now() - 28 * 60000),
          },
          {
            reportId: 'REP-103',
            source: 'FIELD_TEAM',
            text: 'Police Team 02 confirming Gate 1 evacuation underway.',
            reliability: 99,
            reportedAt: new Date(Date.now() - 25 * 60000),
          },
        ],
        assignedResources: ['TEAM-FT04', 'TEAM-AM07', 'TEAM-PD02', 'RES-EQ-01'],
        aiAnalysis: {
          confidenceScore: 94,
          primaryHazard: 'Hydrocarbon BLEVE Explosion & Secondary Toxic Smoke',
          evacuationRadiusMeters: 750,
          recommendedResourceTypes: ['FIRE_TEAM', 'AMBULANCE', 'POLICE_TEAM'],
          summary: 'High explosive vapor cloud formation. Industrial foam blanket deployment critical.',
        },
      },
      {
        incidentId: 'ER-2049',
        title: 'Pressurized Chlorine Gas Rupture at Container Bay',
        type: 'INDUSTRIAL_ACCIDENT',
        description: 'Pressurized ISO container rupture leaking toxic chlorine gas cloud. Downwind drift vector calculating 18 km/h northeast toward commercial district.',
        location: {
          latitude: 28.6410,
          longitude: 77.2340,
          address: 'Docklands Cargo Terminal Bay 14, Port Maritime Zone',
          geometry: { type: 'Point', coordinates: [77.2340, 28.6410] },
        },
        severity: 'CRITICAL',
        priority: 'P1',
        confidence: 91,
        status: 'ESCALATED',
        source: 'SENSOR',
        reports: [
          {
            reportId: 'REP-201',
            source: 'SENSOR',
            text: 'Chlorine sensor CL-09 spike above 42 ppm.',
            reliability: 99,
            reportedAt: new Date(Date.now() - 45 * 60000),
          },
        ],
        assignedResources: ['TEAM-HZ01', 'RES-VEH-04'],
        aiAnalysis: {
          confidenceScore: 91,
          primaryHazard: 'Lethal Airborne Inhalation Hazard',
          evacuationRadiusMeters: 1200,
          recommendedResourceTypes: ['FIRE_TEAM'],
          summary: 'Toxic cloud dispersion towards northern quadrant. Emergency sirens activated.',
        },
      },
      {
        incidentId: 'ER-2050',
        title: 'Multi-Vehicle Chain Highway Collision on Overpass',
        type: 'ROAD_ACCIDENT',
        description: 'High-speed 4-car and heavy freight truck pileup on elevated highway bridge. Occupants entrapped. Both eastbound lanes blocked.',
        location: {
          latitude: 28.5850,
          longitude: 77.1750,
          address: 'Overpass Bridge Km 14, NH-48 Expressway Corridor',
          geometry: { type: 'Point', coordinates: [77.1750, 28.5850] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 96,
        status: 'RESPONDING',
        source: 'EMERGENCY_CALL',
        reports: [
          {
            reportId: 'REP-301',
            source: 'EMERGENCY_CALL',
            text: 'Overturned cargo truck pinned two sedans against highway rail.',
            reliability: 92,
            reportedAt: new Date(Date.now() - 20 * 60000),
          },
        ],
        assignedResources: ['TEAM-AM02', 'TEAM-PD05'],
        aiAnalysis: {
          confidenceScore: 96,
          primaryHazard: 'Structural Highway Entrapment & Severe Fuel Leak',
          evacuationRadiusMeters: 150,
          recommendedResourceTypes: ['AMBULANCE', 'POLICE_TEAM'],
          summary: 'Ambulance 02 delayed +6 min in transit due to gridlock.',
        },
      },
      {
        incidentId: 'ER-2051',
        title: 'Monsoon Flash Flood Underpass Inundation',
        type: 'FLOOD',
        description: 'Torrential runoff stormwater surge submerged low-lying vehicular underpass up to 1.8 meters. Stranded passenger buses confirmed.',
        location: {
          latitude: 28.6550,
          longitude: 77.1920,
          address: 'Underpass Drainage Basin, Metro Zone 5 Riverbank',
          geometry: { type: 'Point', coordinates: [77.1920, 28.6550] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 89,
        status: 'ASSIGNED',
        source: 'CITIZEN',
        reports: [],
        assignedResources: ['TEAM-RT03', 'RES-EQ-02'],
      },
      {
        incidentId: 'ER-2052',
        title: 'Substation Electrical Arc Explosion',
        type: 'FIRE',
        description: 'High-voltage transformer arc explosion knocked out power across 4 hospital feeder lines. Localized secondary oil fire burning.',
        location: {
          latitude: 28.6180,
          longitude: 77.2450,
          address: 'Grid Substation 11-A, Tech Park East Sector',
          geometry: { type: 'Point', coordinates: [77.2450, 28.6180] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 88,
        status: 'ANALYZING',
        source: 'SYSTEM',
        reports: [],
        assignedResources: ['TEAM-FT01'],
      },
      {
        incidentId: 'ER-2053',
        title: 'Commercial High-Rise Fire Alarm & Smoke Ejection',
        type: 'FIRE',
        description: 'Electrical riser smoke spread across 14th to 18th floors in 32-story corporate tower. Automated sprinkler suppression engaged.',
        location: {
          latitude: 28.6340,
          longitude: 77.2150,
          address: 'Titanium Financial Tower, Barakhamba Road',
          geometry: { type: 'Point', coordinates: [77.2150, 28.6340] },
        },
        severity: 'MEDIUM',
        priority: 'P3',
        confidence: 87,
        status: 'NEW',
        source: 'SENSOR',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2054',
        title: 'Collapsed Pedestrian Skywalk Overpass',
        type: 'OTHER',
        description: 'Structural failure of pedestrian skywalk during construction girder lift. Crushed two passenger auto-rickshaws below.',
        location: {
          latitude: 28.6120,
          longitude: 77.1980,
          address: 'Metro Transit Interchange Gate 3',
          geometry: { type: 'Point', coordinates: [77.1980, 28.6120] },
        },
        severity: 'CRITICAL',
        priority: 'P1',
        confidence: 95,
        status: 'PRIORITIZED',
        source: 'FIELD_TEAM',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2055',
        title: 'Mass Food Poisoning at Convention Exhibition Center',
        type: 'MEDICAL_EMERGENCY',
        description: 'Over 85 international delegates experiencing acute gastrointestinal distress and hypotension following catered lunch event.',
        location: {
          latitude: 28.6190,
          longitude: 77.2400,
          address: 'Pragati International Trade Expo Hall 5',
          geometry: { type: 'Point', coordinates: [77.2400, 28.6190] },
        },
        severity: 'MEDIUM',
        priority: 'P3',
        confidence: 92,
        status: 'ASSIGNED',
        source: 'EMERGENCY_CALL',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2056',
        title: 'Earthquake Tremor Felt — Structural Crack in Viaduct',
        type: 'EARTHQUAKE',
        description: 'Magnitude 4.8 seismic tremor triggered automated train halt. Visual inspection reports surface cracks on elevated track pier 44.',
        location: {
          latitude: 28.6470,
          longitude: 77.2100,
          address: 'Northern Railway Elevated Viaduct Pier 44',
          geometry: { type: 'Point', coordinates: [77.2100, 28.6470] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 86,
        status: 'ANALYZING',
        source: 'SENSOR',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2057',
        title: 'Gasoline Tanker Truck Rollover & Spill',
        type: 'ROAD_ACCIDENT',
        description: '20,000-liter octane fuel tanker overturned on roundabout. Fuel gushing into roadside municipal storm drains.',
        location: {
          latitude: 28.6290,
          longitude: 77.1850,
          address: 'Ring Road Roundabout, Dhaula Kuan Ingress',
          geometry: { type: 'Point', coordinates: [77.1850, 28.6290] },
        },
        severity: 'CRITICAL',
        priority: 'P1',
        confidence: 93,
        status: 'RESPONDING',
        source: 'EMERGENCY_CALL',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2058',
        title: 'Hospital Oxygen Tank Manifold Pressure Drop',
        type: 'MEDICAL_EMERGENCY',
        description: 'Cryogenic liquid oxygen secondary valve malfunction caused pressure drop in ICU ward supplying 40 ventilators.',
        location: {
          latitude: 28.6360,
          longitude: 77.2240,
          address: 'Metropolitan Government General Hospital Oxygen Bay',
          geometry: { type: 'Point', coordinates: [77.2240, 28.6360] },
        },
        severity: 'CRITICAL',
        priority: 'P1',
        confidence: 98,
        status: 'RESPONDING',
        source: 'GOVERNMENT',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2059',
        title: 'Warehouse Fire at Timber Storage Yard',
        type: 'FIRE',
        description: 'Heavy timber lumber stack ignited by discarded cigarette. Rapid spread across 2 acres. Nearby residential block threatened.',
        location: {
          latitude: 28.6650,
          longitude: 77.2180,
          address: 'North Timber Market, Azadpur Sector 2',
          geometry: { type: 'Point', coordinates: [77.2180, 28.6650] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 90,
        status: 'ASSIGNED',
        source: 'CITIZEN',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2060',
        title: 'River Embankment Seepage Alert',
        type: 'FLOOD',
        description: 'Rising river water level breached primary clay levee. Water entering informal riverbank settlement colonies.',
        location: {
          latitude: 28.6620,
          longitude: 77.2290,
          address: 'Yamuna Floodplain Ghat 8, Old Bridge',
          geometry: { type: 'Point', coordinates: [77.2290, 28.6620] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 89,
        status: 'RESPONDING',
        source: 'FIELD_TEAM',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2061',
        title: 'School Bus Collision with Concrete Barrier',
        type: 'ROAD_ACCIDENT',
        description: 'School bus brake failure resulted in low-speed impact with bridge divider. 18 minor injuries, 2 severe fractures.',
        location: {
          latitude: 28.5980,
          longitude: 77.2120,
          address: 'Lodhi Road Underbridge Crossroad',
          geometry: { type: 'Point', coordinates: [77.2120, 28.5980] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 95,
        status: 'ON_SCENE',
        source: 'EMERGENCY_CALL',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2062',
        title: 'Underground Sewer Gas Methane Flash Fire',
        type: 'FIRE',
        description: 'Municipal sanitation crew encountered methane pocket explosion while clearing main trunk line. 2 workers injured.',
        location: {
          latitude: 28.6430,
          longitude: 77.2020,
          address: 'Karol Bagh Market Main Conduit',
          geometry: { type: 'Point', coordinates: [77.2020, 28.6430] },
        },
        severity: 'MEDIUM',
        priority: 'P3',
        confidence: 84,
        status: 'RESOLVED',
        source: 'FIELD_TEAM',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2063',
        title: 'Hazardous Ammonia Refrigerant Leak at Ice Factory',
        type: 'INDUSTRIAL_ACCIDENT',
        description: 'Cracked expansion valve leaking pungent ammonia vapor in high-density residential fringe. Evacuation of 3 streets ordered.',
        location: {
          latitude: 28.6510,
          longitude: 77.2410,
          address: 'Old Subzi Mandi Cold Storage Plant',
          geometry: { type: 'Point', coordinates: [77.2410, 28.6510] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 91,
        status: 'RESPONDING',
        source: 'CITIZEN',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2064',
        title: 'Residential 3-Story Building Cracking & Tilting',
        type: 'OTHER',
        description: 'Basement excavation in adjacent plot destabilized foundation of inhabited residential apartments. 12 families evacuated.',
        location: {
          latitude: 28.6380,
          longitude: 77.1890,
          address: 'Rajendra Nagar Block 4, House 18',
          geometry: { type: 'Point', coordinates: [77.1890, 28.6380] },
        },
        severity: 'MEDIUM',
        priority: 'P3',
        confidence: 88,
        status: 'ON_SCENE',
        source: 'CITIZEN',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2065',
        title: 'Cardiac Arrest in Crowded Metro Station Concourse',
        type: 'MEDICAL_EMERGENCY',
        description: '54-year-old commuter collapsed with sudden cardiac arrest. Station AED deployed by security, paramedic unit requested.',
        location: {
          latitude: 28.6290,
          longitude: 77.2180,
          address: 'Rajiv Chowk Metro Underground Hub Gate 4',
          geometry: { type: 'Point', coordinates: [77.2180, 28.6290] },
        },
        severity: 'MEDIUM',
        priority: 'P3',
        confidence: 97,
        status: 'ON_SCENE',
        source: 'EMERGENCY_CALL',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2066',
        title: 'Chemical Acid Tanker Leakage on Flyover',
        type: 'INDUSTRIAL_ACCIDENT',
        description: 'Hydrochloric acid dripping from corroded drainage valve on elevated expressway. Fuming vapor irritating commuter eyes.',
        location: {
          latitude: 28.5740,
          longitude: 77.1680,
          address: 'Mahipalpur Flyover Summit, Airport Road',
          geometry: { type: 'Point', coordinates: [77.1680, 28.5740] },
        },
        severity: 'HIGH',
        priority: 'P2',
        confidence: 92,
        status: 'ASSIGNED',
        source: 'FIELD_TEAM',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2067',
        title: 'Transformer Spark Fire Near High-Density Slum',
        type: 'FIRE',
        description: 'Overheated distribution transformer ignited low-hanging cables above dense informal settlement. Rapid containment active.',
        location: {
          latitude: 28.6590,
          longitude: 77.2150,
          address: 'Seelampur Transit Cluster Lane 9',
          geometry: { type: 'Point', coordinates: [77.2150, 28.6590] },
        },
        severity: 'MEDIUM',
        priority: 'P3',
        confidence: 85,
        status: 'RESPONDING',
        source: 'CITIZEN',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2068',
        title: 'Multi-Vehicle Collision in Fog on Expressway',
        type: 'ROAD_ACCIDENT',
        description: 'Low-visibility early morning pileup involving 6 commuter sedans. Minor injuries, lanes cleared to shoulder.',
        location: {
          latitude: 28.5600,
          longitude: 77.1500,
          address: 'Expressway Gateway Km 28',
          geometry: { type: 'Point', coordinates: [77.1500, 28.5600] },
        },
        severity: 'LOW',
        priority: 'P4',
        confidence: 90,
        status: 'RESOLVED',
        source: 'EMERGENCY_CALL',
        reports: [],
        assignedResources: [],
      },
      {
        incidentId: 'ER-2069',
        title: 'Basement Inundation at Data Center Facility',
        type: 'FLOOD',
        description: 'Water main rupture flooded backup diesel generator room with 1 meter of muddy water. Essential cooling at risk.',
        location: {
          latitude: 28.6210,
          longitude: 77.2480,
          address: 'Cyber Tech Park Sector 14, Okhla Hub',
          geometry: { type: 'Point', coordinates: [77.2480, 28.6210] },
        },
        severity: 'LOW',
        priority: 'P4',
        confidence: 89,
        status: 'NEW',
        source: 'SENSOR',
        reports: [],
        assignedResources: [],
      },
    ];

    await IncidentModel.insertMany(incidents);
    console.log(`[Seed] Seeded ${incidents.length} Incidents.`);

    console.log('====================================================');
    console.log('✓ DATABASE SEED COMPLETED SUCCESSFULLY');
    console.log(`  Users: ${users.length}`);
    console.log(`  Incidents: ${incidents.length}`);
    console.log(`  Resources: ${resources.length}`);
    console.log(`  Response Teams: ${teams.length}`);
    console.log(`  Facilities: ${facilities.length}`);
    console.log('====================================================');

    await mongoose.disconnect();
    console.log('[Seed] Disconnected from database.');
    process.exit(0);
  } catch (error) {
    console.error('[Seed] Database seeding failed:', error);
    process.exit(1);
  }
};

seedDatabase();
