/**
 * Centralized Role-Based Operational Permissions Matrix for EmergenX (Phase 30)
 */

export const PERMISSIONS = {
  // Incidents
  INCIDENT_CREATE: 'INCIDENT_CREATE',
  INCIDENT_READ: 'INCIDENT_READ',
  INCIDENT_UPDATE: 'INCIDENT_UPDATE',
  INCIDENT_RESOLVE: 'INCIDENT_RESOLVE',
  INCIDENT_DELETE: 'INCIDENT_DELETE',

  // Resources
  RESOURCE_READ: 'RESOURCE_READ',
  RESOURCE_CREATE: 'RESOURCE_CREATE',
  RESOURCE_UPDATE: 'RESOURCE_UPDATE',
  RESOURCE_ASSIGN: 'RESOURCE_ASSIGN',
  RESOURCE_RELEASE: 'RESOURCE_RELEASE',
  RESOURCE_DELETE: 'RESOURCE_DELETE',

  // Teams
  TEAM_READ: 'TEAM_READ',
  TEAM_CREATE: 'TEAM_CREATE',
  TEAM_UPDATE: 'TEAM_UPDATE',
  TEAM_ASSIGN: 'TEAM_ASSIGN',
  TEAM_DELETE: 'TEAM_DELETE',

  // Facilities & Hospitals
  FACILITY_READ: 'FACILITY_READ',
  FACILITY_UPDATE: 'FACILITY_UPDATE',

  // Escalations
  ESCALATION_READ: 'ESCALATION_READ',
  ESCALATION_TRIGGER: 'ESCALATION_TRIGGER',
  ESCALATION_ACKNOWLEDGE: 'ESCALATION_ACKNOWLEDGE',
  ESCALATION_RESOLVE: 'ESCALATION_RESOLVE',

  // Notifications
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',

  // AI Decision Support
  AI_ANALYZE: 'AI_ANALYZE',
  AI_OVERRIDE: 'AI_OVERRIDE',
  AI_CHAT: 'AI_CHAT',

  // Simulation Engine
  SIMULATION_READ: 'SIMULATION_READ',
  SIMULATION_START: 'SIMULATION_START',
  SIMULATION_ADVANCE: 'SIMULATION_ADVANCE',
  SIMULATION_STOP: 'SIMULATION_STOP',

  // Audit Logs
  AUDIT_READ: 'AUDIT_READ',

  // Analytics
  ANALYTICS_READ: 'ANALYTICS_READ',

  // System & Users & Synthetic Data
  SYSTEM_MANAGE: 'SYSTEM_MANAGE',
  USER_MANAGE: 'USER_MANAGE',
  SYNTHETIC_DATA_GENERATE: 'SYNTHETIC_DATA_GENERATE',
};

// All permissions array for Admin role
const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
  ADMIN: ALL_PERMISSIONS,

  OPERATOR: [
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.INCIDENT_READ,
    PERMISSIONS.INCIDENT_UPDATE,
    PERMISSIONS.INCIDENT_RESOLVE,
    PERMISSIONS.RESOURCE_READ,
    PERMISSIONS.RESOURCE_ASSIGN,
    PERMISSIONS.RESOURCE_RELEASE,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_ASSIGN,
    PERMISSIONS.FACILITY_READ,
    PERMISSIONS.FACILITY_UPDATE,
    PERMISSIONS.ESCALATION_READ,
    PERMISSIONS.ESCALATION_TRIGGER,
    PERMISSIONS.ESCALATION_ACKNOWLEDGE,
    PERMISSIONS.ESCALATION_RESOLVE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_CREATE,
    PERMISSIONS.AI_ANALYZE,
    PERMISSIONS.AI_OVERRIDE,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.SIMULATION_READ,
    PERMISSIONS.SIMULATION_START,
    PERMISSIONS.SIMULATION_ADVANCE,
    PERMISSIONS.SIMULATION_STOP,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],

  FIELD_COORDINATOR: [
    PERMISSIONS.INCIDENT_READ,
    PERMISSIONS.INCIDENT_UPDATE, // For tactical/status updates
    PERMISSIONS.RESOURCE_READ,
    PERMISSIONS.RESOURCE_UPDATE, // For GPS / status update
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_UPDATE, // For GPS / status update
    PERMISSIONS.FACILITY_READ,
    PERMISSIONS.ESCALATION_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.SIMULATION_READ,
  ],

  MEDICAL_COORDINATOR: [
    PERMISSIONS.INCIDENT_READ,
    PERMISSIONS.RESOURCE_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.FACILITY_READ,
    PERMISSIONS.FACILITY_UPDATE, // Bed & trauma capacity updates
    PERMISSIONS.ESCALATION_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.SIMULATION_READ,
  ],

  RESPONDER: [
    PERMISSIONS.INCIDENT_READ,
    PERMISSIONS.RESOURCE_READ,
    PERMISSIONS.RESOURCE_UPDATE, // For own location / transit status
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_UPDATE,
    PERMISSIONS.FACILITY_READ,
    PERMISSIONS.ESCALATION_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.SIMULATION_READ,
  ],

  VIEWER: [
    PERMISSIONS.INCIDENT_READ,
    PERMISSIONS.RESOURCE_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.FACILITY_READ,
    PERMISSIONS.ESCALATION_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.SIMULATION_READ,
  ],
};

/**
 * Check if a given role possesses a specific permission
 */
export const hasPermission = (role, permission) => {
  if (!role || !permission) return false;
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
};

export default {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
